import json
import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

from signals.groq_signal import run_groq_signal
from signals.stylometric_signal import run_stylometric_signal

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    storage_uri="memory://",
    default_limits=[],
)

AUDIT_LOG_PATH = os.path.join(os.path.dirname(__file__), "audit_log.json")


def _load_log() -> list:
    if not os.path.exists(AUDIT_LOG_PATH):
        return []
    with open(AUDIT_LOG_PATH, "r") as f:
        content = f.read().strip()
    if not content:
        return []
    return json.loads(content)


def _save_log(entries: list) -> None:
    with open(AUDIT_LOG_PATH, "w") as f:
        json.dump(entries, f, indent=2)


def _get_attribution_and_label(confidence: float) -> tuple[str, str]:
    if confidence >= 0.85:
        return (
            "likely_ai",
            "This content was likely generated by AI. Confidence: High",
        )
    elif confidence >= 0.60:
        return (
            "uncertain_leaning_ai",
            "We were unable to determine with confidence whether this content was "
            "human or AI-generated, though it shows some characteristics of "
            "AI-generated content. If you believe this is incorrect, you may submit an appeal.",
        )
    elif confidence >= 0.40:
        return (
            "uncertain_leaning_human",
            "We were unable to determine with confidence whether this content was "
            "human or AI-generated, though it shows some characteristics of human "
            "writing. If you believe this is incorrect, you may submit an appeal.",
        )
    else:
        return (
            "likely_human",
            "This content appears to be human-written. Confidence: High",
        )


@app.route("/submit", methods=["POST"])
@limiter.limit("3 per minute")
@limiter.limit("20 per day")
def submit():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = body.get("text", "").strip()
    creator_id = body.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    try:
        signal_1 = run_groq_signal(text)
    except Exception as e:
        return jsonify({"error": f"Signal 1 (Groq) failed: {str(e)}"}), 502

    signal_1_score = signal_1["score"]
    signal_1_reasoning = signal_1["reasoning"]

    signal_2 = run_stylometric_signal(text)
    signal_2_score = signal_2["score"]

    print(f"[signals] signal_1={signal_1_score:.4f}  signal_2={signal_2_score:.4f}")

    confidence = round((0.6 * signal_1_score) + (0.4 * signal_2_score), 4)
    attribution, label = _get_attribution_and_label(confidence)

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "signal_1_score": signal_1_score,
        "signal_1_reasoning": signal_1_reasoning,
        "signal_2_score": signal_2_score,
        "status": "classified",
    }

    log = _load_log()
    log.append(entry)
    _save_log(log)

    return jsonify(
        {
            "content_id": content_id,
            "attribution": attribution,
            "confidence": confidence,
            "label": label,
        }
    ), 201


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = body.get("content_id", "").strip()
    creator_reasoning = body.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    log = _load_log()
    entry = next((e for e in log if e["content_id"] == content_id), None)
    if entry is None:
        return jsonify({"error": f"content_id not found: {content_id}"}), 404

    entry["status"] = "under_review"
    entry["appeal_reasoning"] = creator_reasoning
    entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
    _save_log(log)

    return jsonify(
        {
            "message": "Appeal received. Your submission has been flagged for human review.",
            "content_id": content_id,
            "status": "under_review",
        }
    ), 200


@app.route("/log", methods=["GET"])
def get_log():
    log = _load_log()
    return jsonify(log), 200


if __name__ == "__main__":
    app.run(debug=True)
