import json
import os

from groq import Groq

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

_PROMPT_TEMPLATE = """Analyze the following text and determine whether it was written by a human or generated by an AI.

Evaluate based on semantic and stylistic properties: word choice, sentence flow, coherence patterns, hedging language, and overall writing "feel".

Return ONLY a JSON object with exactly two fields:
- "score": a float between 0.0 and 1.0, where 1.0 means definitely AI-generated and 0.0 means definitely human-written
- "reasoning": a short string (1-2 sentences) explaining your assessment

No preamble, no markdown, no text outside the JSON object.

Text to analyze:
\"\"\"
{text}
\"\"\""""


def run_groq_signal(text: str) -> dict:
    """Call Groq LLM to score text for AI likelihood.

    Returns a dict with 'score' (float 0–1) and 'reasoning' (str).
    Raises ValueError if the model returns unparseable output.
    """
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": _PROMPT_TEMPLATE.format(text=text)}],
        temperature=0,
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        raise ValueError(f"Groq returned non-JSON output: {raw!r}")

    if "score" not in result or "reasoning" not in result:
        raise ValueError(f"Groq response missing required fields: {result}")

    result["score"] = float(result["score"])
    return result
